### ISSUE TITLE
Percentages in category graph should be to 2 decimal places

### ISSUE THREAD

**Issue by ColdHeat** [CTFd/core-beta#12]
Way too long here 

<img width="669" alt="image" src="https://user-images.githubusercontent.com/166333/172920895-02c3fab5-df31-4dfd-8a20-5bc30c34af01.png">

**Comment by ColdHeat** [comment]
@ddomdel This should be a fairly easy fix. You're looking for all the code that looks like this: https://github.com/CTFd/core-beta/blob/main/assets/js/users/public.js#L19.

**Comment by ddomdel** [comment]
Where can I find this in the interface? Is it in these pages? `demo.ctfd.io/user` or `demo.ctfd.io/team`
![image](https://user-images.githubusercontent.com/78736225/182337248-90da1bc3-45a5-4c62-9ee8-31bb57f481af.png)
![image](https://user-images.githubusercontent.com/78736225/182337305-d17d190b-938e-466f-ab51-7ee55b35576b.png)

**Comment by ddomdel** [comment]
Pull request https://github.com/CTFd/core-beta/pull/20
