### ISSUE TITLE
The scoreboard graph doesn't change alongside the scoreboard details

### ISSUE THREAD

**Issue by reteps** [CTFd/core-beta#91]
https://github.com/CTFd/CTFd/blob/master/CHANGELOG.md#370--2024-02-26

![image](https://github.com/user-attachments/assets/90971b60-9bcb-4ed8-8557-1aae935b51eb)
![image](https://github.com/user-attachments/assets/e76d65f9-bb7d-4532-868d-6f6ddb8b36c2)

**Comment by reteps** [comment]
You can upstream https://github.com/sigpwny/sigpwny-core-beta/commit/571748d96f1627a410beedf1b78eb5b2c2ef740f if you want @ColdHeat

**Comment by ColdHeat** [comment]
@reteps If you have any spare time I can merge the PR or use it as a base. If not I will get to this later today hopefully.

**Comment by ColdHeat** [comment]
Hmm this needs CTFd.js changes as well
